apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  # Exposed service on port 80 might be vulnerable in production
